disabled_rules: # rule identifiers to exclude from running
  - function_parameter_count

opt_in_rules: # some rules are only opt-in
  - attributes
  - explicit_init
  - closure_spacing
  - empty_count
  - empty_string
  - trailing_newline
  - colon
  - comma_inheritance
  - implicitly_unwrapped_optional

included: # paths to include during linting. `--path` is ignored if present.
  - LyricFy

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Project/R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning

force_try:
  severity: warning

type_body_length:
  - 300 # warning
  - 400 # error

# or they can set both explicitly
file_length:
  warning: 500
  error: 800

 # warn user when using 3 values in tuple, give error if there are 4
large_tuple:
   - 3
   - 4
   
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names

identifier_name:
  min_length: 2
  max_length: 30

type_name:
  min_length: 4
  max_length:
    warning: 30
    error: 35
  excluded: iPhone # excluded via string
reporter: "xcode"
